name: Java Test Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distibution: 'adopt'

      - name: Compile Test Code
        run: javac MathTest.java

      - name: Run Java test
        run: java TestMath
